spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/simpletodolist
    username: todolist
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    store-type: redis

  redis:
    host: localhost
    password:
    port: 6379

logging:
  level:
    org:
      springframework:
        web: debug
