spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

  session:
    store-type: redis

  datasource:
    url: jdbc:mariadb://localhost:3306/simpletodolist
    username: todolist
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
