spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/simpletodolist
    username: todolistmanager
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile
