spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: ${JAWSDB_MARIA_URL}
    username: ${JAWSDB_MARIA_USERNAME}
    password: ${JAWSDB_MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 9

server:
  error:
    include-message: always
