spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: ${MARIADB10_URL}
    username: ${MARIADB10_USERNAME}
    password: ${MARIADB10_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      maximum-pool-size: 9 # on heroku environment.

  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}

